### ISSUE TITLE
It will fail when sending a Manual deal to a miner of calibration network

### ISSUE THREAD

**Issue by XuSenqi** [filswan/go-swan-client#145]
v0.1.0-rc1

I have created a Manual-bid task. Then It fails when sending a Manual deal.

$ swan-client deal -json /tmp/tasks/2022-05-29_13\:18\:48/swan-task-7k9sl4-metadata.json -miner t035739
time="2022-05-30 09:58:57.458" level=info msg="metadata json file:/tmp/tasks/2022-05-29_13:18:48/swan-task-7k9sl4-metadata.json" func=sendDeal file="main.go:220"
time="2022-05-30 09:58:57.458" level=info msg="output dir:" func=sendDeal file="main.go:221"
time="2022-05-30 09:58:57.458" level=info msg="miner:t035739" func=sendDeal file="main.go:222"
time="2022-05-30 09:58:57.459" level=info msg="current epoch:1852315" func=GetConfDeal file="conf_deal.go:46"
time="2022-05-30 09:58:57.459" level=info msg="start epoch:1863955" func=GetConfDeal file="conf_deal.go:48"
time="2022-05-30 09:58:57.459" level=info msg="/tmp/tasks/2022-05-30_09:58:57" func=SendDeals file="deal.go:26"
time="2022-05-30 09:58:57.459" level=info msg="stat /tmp/tasks/2022-05-30_09:58:57: no such file or directory" func=GetPathType file="file.go:65"
time="2022-05-30 09:58:57.459" level=info msg="/tmp/tasks/2022-05-30_09:58:57 created" func=CreateOutputDir file="common.go:199"
time="2022-05-30 09:58:59.519" level=info msg="Getting My swan tasks info" func=SwanGetOfflineDealsByTaskUuid file="task.go:242"
time="2022-05-30 09:59:00.397" level=error msg="http status: 500 INTERNAL SERVER ERROR, code:500, url:https://api.filswan.com/tools/check_datacap?address=t3rx7zig6nalm54nmnavc2oim6zfaos3cawjrqjxowvmpio2tmaqkzehim6iz554ynqi7ss7pcxf6it5tr3lwq" func=HttpRequest file="restful.go:121"
time="2022-05-30 09:59:00.397" level=error func=HttpGetNoToken file="restful.go:45"
time="2022-05-30 09:59:00.397" level=error msg="no response from:https://api.filswan.com/tools/check_datacap?address=t3rx7zig6nalm54nmnavc2oim6zfaos3cawjrqjxowvmpio2tmaqkzehim6iz554ynqi7ss7pcxf6it5tr3lwq" func=CheckDatacap file="tool.go:22"
time="2022-05-30 09:59:00.397" level=error msg="no response from:https://api.filswan.com/tools/check_datacap?address=t3rx7zig6nalm54nmnavc2oim6zfaos3cawjrqjxowvmpio2tmaqkzehim6iz554ynqi7ss7pcxf6it5tr3lwq" func=SendDeals file="deal.go:68"
time="2022-05-30 09:59:00.397" level=error msg="no response from:https://api.filswan.com/tools/check_datacap?address=t3rx7zig6nalm54nmnavc2oim6zfaos3cawjrqjxowvmpio2tmaqkzehim6iz554ynqi7ss7pcxf6it5tr3lwq" func=sendDeal file="main.go:227"
time="2022-05-30 09:59:00.397" level=error msg="no response from:https://api.filswan.com/tools/check_datacap?address=t3rx7zig6nalm54nmnavc2oim6zfaos3cawjrqjxowvmpio2tmaqkzehim6iz554ynqi7ss7pcxf6it5tr3lwq" func=execSubCmd file="main.go:46"

**Comment by Normalnoise** [comment]
@XuSenqi  Do you send a private task in Calibration network?

**Comment by XuSenqi** [comment]
@Normalnoise 

This is my config.toml.

[sender]
bid_mode = 0
offline_mode = false
output_dir = "/tmp/tasks"
public_deal = false
verified_deal = true
fast_retrieval = true
skip_confirmation = false
generate_md5 = false
wallet = "t3rx7zig6nalm54nmnavc2oim6zfaos3cawjrqjxowvmpio2tmaqkzehim6iz554ynqi7ss7pcxf6it5tr3lwq"
max_price = "0.00000000005"
start_epoch_hours = 96
expire_days = 4
gocar_file_size_limit = 8589934592
gocar_folder_based = false
duration = 1051200    # Duration is expressed in blocks (1 block is equivalent to 30s).
relative_epoch_from_main_network = 0 # Your network current epoch - main network current epoch



It fails when sending a private task.


ubuntu@10-13-27-225:~/go-swan-client$ swan-client task -input-dir /home/ubuntu/test_swan_client/outputDir/ -description "task test 3" -miner t035577
time="2022-05-30 10:49:32.254" level=info msg="your input dir: /home/ubuntu/test_swan_client/outputDir/" func=createTask file="main.go:175"
time="2022-05-30 10:49:32.254" level=info msg="current epoch:1852416" func=GetConfDeal file="conf_deal.go:46"
time="2022-05-30 10:49:32.254" level=info msg="start epoch:1864056" func=GetConfDeal file="conf_deal.go:48"
time="2022-05-30 10:49:32.255" level=info msg="stat /tmp/tasks/2022-05-30_10:49:32: no such file or directory" func=GetPathType file="file.go:65"
time="2022-05-30 10:49:32.255" level=info msg="/tmp/tasks/2022-05-30_10:49:32 created" func=CreateOutputDir file="common.go:199"
time="2022-05-30 10:49:32.255" level=info msg="you output dir: /tmp/tasks/2022-05-30_10:49:32" func=CreateTask file="task.go:46"
time="2022-05-30 10:49:32.255" level=info msg="getting price for miner:t035577" func=CheckDealConfig file="common.go:114"
time="2022-05-30 10:49:32.277" level=info msg="miner:t035577,price is:0.00000000005" func=CheckDealConfig file="common.go:130"
time="2022-05-30 10:49:32.277" level=info msg="Do you confirm to submit the deal?" func=LotusClientStartDeal file="client.go:559"
time="2022-05-30 10:49:32.278" level=info msg="Press Y/y to continue, other key to quit" func=LotusClientStartDeal file="client.go:560"
y
time="2022-05-30 10:49:40.964" level=info msg="[{\"Data\":{\"TransferType\":\"manual\",\"Root\":{\"/\":\"bafykbzaceayo2cij22xerz2qhpvu4ik6ddmva24zk572i6pnnvf6avcxr35ki\"},\"PieceCid\":{\"/\":\"baga6ea4seaqli4pivqbdgz6lrtxi4qr64vkxzygslotmxtwcs6eydqwhfrmksfa\"},\"PieceSize\":266338304},\"Wallet\":\"t3rx7zig6nalm54nmnavc2oim6zfaos3cawjrqjxowvmpio2tmaqkzehim6iz554ynqi7ss7pcxf6it5tr3lwq\",\"Miner\":\"t035577\",\"EpochPrice\":\"12500000\",\"MinBlocksDuration\":1051200,\"DealStartEpoch\":1864056,\"FastRetrieval\":true,\"VerifiedDeal\":true}]" func=LotusClientStartDeal file="client.go:606"
time="2022-05-30 10:49:40.970" level=info msg="deal CID:bafyreih6qoqiy33iw6s4jh33gzjs3jt6mmlurvg5jttvz26lxyzvixe4ki" func=LotusClientStartDeal file="client.go:635"
time="2022-05-30 10:49:40.972" level=info msg="task:swan-task-vr2v2y, deal CID:bafyreih6qoqiy33iw6s4jh33gzjs3jt6mmlurvg5jttvz26lxyzvixe4ki, start epoch:1864056, deal sent to t035577 successfully" func=SendDeals2Miner file="deal.go:147"
time="2022-05-30 10:49:40.972" level=info msg="1 deal(s) has(ve) been sent for task:swan-task-vr2v2y" func=SendDeals2Miner file="deal.go:150"
time="2022-05-30 10:49:40.973" level=info msg="deal: metadata json generated: /tmp/tasks/2022-05-30_10:49:32/swan-task-vr2v2y-deals.json" func=WriteCarFilesToJsonFile file="common.go:239"
time="2022-05-30 10:49:40.973" level=info msg="deal: metadata csv generated: /tmp/tasks/2022-05-30_10:49:32/swan-task-vr2v2y-deals.csv" func=WriteCarFilesToCsvFile file="common.go:341"
time="2022-05-30 10:49:40.973" level=info msg="Swan task CSV Generated: /tmp/tasks/2022-05-30_10:49:32/swan-task-vr2v2y.csv" func=CreateCsv4TaskDeal file="common.go:349"
time="2022-05-30 10:49:40.973" level=info msg="task: metadata json generated: /tmp/tasks/2022-05-30_10:49:32/swan-task-vr2v2y-metadata.json" func=WriteCarFilesToJsonFile file="common.go:239"
time="2022-05-30 10:49:40.973" level=info msg="task: metadata csv generated: /tmp/tasks/2022-05-30_10:49:32/swan-task-vr2v2y-metadata.csv" func=WriteCarFilesToCsvFile file="common.go:341"
time="2022-05-30 10:49:40.973" level=info msg="Swan task CSV Generated: /tmp/tasks/2022-05-30_10:49:32/swan-task-vr2v2y.csv" func=CreateCsv4TaskDeal file="common.go:349"
time="2022-05-30 10:49:40.973" level=info msg="Working in Online Mode. A swan task will be created on the filwan.com after process done. " func=SendTask2Swan file="task.go:192"

time="2022-05-30 10:49:43.259" level=error msg="error:fail,Create task failed.Please provide miner fid for non public deal." func=SwanCreateTask file="task.go:64"
time="2022-05-30 10:49:43.259" level=error msg="error:fail,Create task failed.Please provide miner fid for non public deal." func=SendTask2Swan file="task.go:201"
time="2022-05-30 10:49:43.259" level=error msg="error:fail,Create task failed.Please provide miner fid for non public deal." func=CreateTask file="task.go:168"
time="2022-05-30 10:49:43.259" level=error msg="error:fail,Create task failed.Please provide miner fid for non public deal." func=createTask file="main.go:181"
time="2022-05-30 10:49:43.259" level=error msg="error:fail,Create task failed.Please provide miner fid for non public deal." func=execSubCmd file="main.go:46"

**Comment by XuSenqi** [comment]
After upgrading the client, the error msg changes.
So close the issue.
